### ISSUE TITLE
Illustrate how concrete types depend on abstract types

### ISSUE THREAD

**Issue by korenmiklos** [cpfiffer/julia-bootcamp-2022#3]
https://github.com/cpfiffer/julia-bootcamp-2022/blob/71a9b564b6c55e84fd837b0082c19e69d953f06b/session-1/project.jl#L10

Did you want to add `<: StandardErrorEstimator` here?

**Comment by cpfiffer** [comment]
I did indeed! Thank you for catching that.

**Comment by cpfiffer** [comment]
Fixed in 1095f7cb03c689bd85f0560c4a2fa86b7f78e4ff
