### ISSUE TITLE
potential typo in session 5 lecture notes

### ISSUE THREAD

**Issue by YuchengZ-Fin** [cpfiffer/julia-bootcamp-2022#5]
In the first example with beta prior and binomial likelihood, the second argument for posterior beta distribution would leave N outside of the sum?

**Comment by cpfiffer** [comment]
Hm, I did a cursory look through but couldn't find exactly what you're referring to -- could you take a screenshot or something?

**Comment by YuchengZ-Fin** [comment]
![image](https://user-images.githubusercontent.com/54778958/197835051-872e4ac8-2cd2-4ad0-9b93-51ae259a4239.png)

**Comment by cpfiffer** [comment]
Ah, thanks. That's correct, as per [this table](https://en.wikipedia.org/wiki/Conjugate_prior#Table_of_conjugate_distributions). Or at least I believe so.
