### ISSUE TITLE
Add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [cpfiffer/julia-bootcamp-2022#7]
I suggest adding topics such as `julia`, `statistics`, `bayesian-statistics`, `econometrics`, `numerical-optimization`, `autodiff` in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by just-cameron** [comment]
Added! Thank you so much.
